# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Viliam
email: viliam@brozman.sk
description: > # this means to ignore newlines until "baseurl:"
  zmeň seba, zmeníš svet
  
  
  
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://vili.am" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: webjeda
copyright:
   name: Viliam
   link: 'https://vili.am'

# Build settings
future: true
markdown: kramdown
permalink: /:title/
paginate: 9
paginate_path: /page:num/

# Tracker
analytics: UA-6810782-25

# Comments
disqus-shortname: http-vili-am

#social
facebook: http://facebook.com/viliammmmm/

#facebook like box
#fb-app-id: 1861898717394681
#fb-page-url: http://facebook.com/viliammmmm
#fb-page-title: Viliam

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]

# Open Graph nastavenia
og_image: images/webjeda-logo-big.jpg # Default image for Open Graph tag
og_image_type: image/jpeg
og_image_width: 400
og_image_height: 250

